name: ci

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/flexwie/bc100
          tag-custom: latest
          tag-semver: |
            {{raw}}
      - name: Docker meta init
        id: meta_init
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/flexwie/bc100-init
          tag-custom: latest
          tag-semver: |
            {{raw}}
      - name: Build and push app image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Build and push init image
        uses: docker/build-push-action@v3
        with:
          file: init.Dockerfile
          push: true
          tags: ${{ steps.meta_init.outputs.tags }}
          labels: ${{ steps.meta_init.outputs.labels }}
